[Eth]
NetworkId = $ETH_CHAIN_ID
SyncMode = "full"
NoPruning = true

[Node]
DataDir = "/data"
IPCPath = "geth.ipc"
HTTPHost = "0.0.0.0"
HTTPPort = 8178
HTTPCors = ["*"]
HTTPVirtualHosts = ["*"]
HTTPModules = ["web3", "eth", "txpool", "debug", "personal", "db", "eth"]
WSHost = "0.0.0.0"
WSPort = 8546
WSOrigins = ["*"]

[Node.P2P]
MaxPeers = 25
NoDiscovery = true